-- Typed models for the IamSmart SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class MobileRegistrationPoint
---@field district? string
---@field id? string
---@field latitude? number
---@field location? string
---@field locationEn? string
---@field locationZh? string
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field region? string
---@field remarks? string
---@field schedule? table

---@class MobileRegistrationPointListMatch
---@field district? string
---@field id? string
---@field latitude? number
---@field location? string
---@field locationEn? string
---@field locationZh? string
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field region? string
---@field remarks? string
---@field schedule? table

---@class RegistrationServiceCounter
---@field address? string
---@field addressEn? string
---@field addressZh? string
---@field district? string
---@field id? string
---@field latitude? number
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field operatingHours? string
---@field region? string
---@field remarks? string
---@field services? table
---@field telephone? string

---@class RegistrationServiceCounterListMatch
---@field address? string
---@field addressEn? string
---@field addressZh? string
---@field district? string
---@field id? string
---@field latitude? number
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field operatingHours? string
---@field region? string
---@field remarks? string
---@field services? table
---@field telephone? string

---@class SelfRegistrationKiosk
---@field address? string
---@field addressEn? string
---@field addressZh? string
---@field availability? string
---@field district? string
---@field floor? string
---@field id? string
---@field latitude? number
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field operatingHours? string
---@field region? string
---@field remarks? string

---@class SelfRegistrationKioskListMatch
---@field address? string
---@field addressEn? string
---@field addressZh? string
---@field availability? string
---@field district? string
---@field floor? string
---@field id? string
---@field latitude? number
---@field longitude? number
---@field name? string
---@field nameEn? string
---@field nameZh? string
---@field operatingHours? string
---@field region? string
---@field remarks? string

local M = {}

return M
